### ISSUE TITLE
Hello, are you implementing the algorithm of this paper?

### ISSUE THREAD

**Issue by wanghuohuo0716** [zhongshun/RA-L-2018#1]
hello, zhongshun:  

  I saw the picture of your repo, are they the results of this paper, 《Intercepting Rogue Robots: An Algorithm for Capturing Multiple Evaders with Multiple Pursuers》 by Alyssa Pierson.

 Thank you!

![image](https://user-images.githubusercontent.com/20619811/64775405-a90d4b00-d588-11e9-9920-c2b779bd8cfb.png)

**Comment by zhongshun** [comment]
Hello,

That's not my works, this is from Prof. Mac Schwager from Stanford. You can contact him or his student Zijian Wang (http://web.stanford.edu/~zjwang/)
________________________________
发件人: Yan Wang <notifications@github.com>
发送时间: 2019年9月12日 18:15
收件人: zhongshun/RA-L-2018 <RA-L-2018@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zhongshun/RA-L-2018] Hello, are you implementing the algorithm of this paper? (#1)


hello, zhongshun:

I saw the picture of your repo, are they the results of this paper, 《Intercepting Rogue Robots: An Algorithm for Capturing Multiple Evaders with Multiple Pursuers》 by Alyssa Pierson.

Thank you!

[image]<https://user-images.githubusercontent.com/20619811/64775405-a90d4b00-d588-11e9-9920-c2b779bd8cfb.png>

―

**Comment by wanghuohuo0716** [comment]
ok，thanks~

**Comment by wanghuohuo0716** [comment]
hello, I have finished the implementation of this paper~
https://github.com/wanghuohuo0716/hanting_based_on_voronoi
![hanting](https://user-images.githubusercontent.com/20619811/65411082-8ef02a00-de1e-11e9-9688-e5957c0df3b7.gif)
